INSERT INTO countries (name, abbreviation) VALUES ('Australia', 'AUS'),
                                                  ('Austria', 'AUT'),
                                                  ('Great Britain', 'GBR'),
                                                  ('Germany', 'GER'),
                                                  ('Netherlands', 'NED'),
                                                  ('Mexico', 'MEX'),
                                                  ('Poland', 'POL'),
                                                  ('Spain', 'ESP'),
                                                  ('France', 'FRA'),
                                                  ('Finland', 'FIN'),
                                                  ('Denmark', 'DEN'),
                                                  ('Canada', 'CAN'),
                                                  ('Japan', 'JPN'),
                                                  ('Italy', 'ITA'),
                                                  ('Malaysia', 'MAS'),
                                                  ('China', 'CHN'),
                                                  ('United Arab Emirate', 'UAE'),
                                                  ('Monaco', 'MON'),
                                                  ('Hungary', 'HUN'),
                                                  ('Belgium', 'BEL'),
                                                  ('Singapore', 'SGP'),
                                                  ('Russian', 'RUS'),
                                                  ('Brazil', 'BRA'),
                                                  ('United States of America', 'USA'),
                                                  ('India', 'IND'),
                                                  ('Switzerland', 'SUI'),
                                                  ('Venezuela', 'VEN'),
                                                  ('Sweden', 'SWE'),
                                                  ('New Zealand', 'NZL'),
                                                  ('Poland', 'POL'),
                                                  ('Bahrain', 'BRN'),
                                                  ('Azerbaijan', 'AZE'),
                                                  ('Portugal', 'POR'),
                                                  ('Turkey', 'TUR'),
                                                  ('Thailand', 'THA');

INSERT INTO teams (name, country_id) VALUES ('Mercedes AMG Petronas Motorsport', (select id from countries where abbreviation = 'GER' limit 1)),
                                            ('Scuderia Ferrari', (select id from countries where abbreviation = 'ITA' limit 1)),
                                            ('Aston Martin Red Bull Racing', (select id from countries where abbreviation = 'AUT' limit 1)),
                                            ('Force India F1 Team', (select id from countries where abbreviation = 'IND' limit 1)),
                                            ('Lotus Renault', (select id from countries where abbreviation = 'GBR' limit 1)),
                                            ('Scuderia AlphaTauri', (select id from countries where abbreviation = 'ITA' limit 1)),
                                            ('Sauber F1 Team', (select id from countries where abbreviation = 'SUI' limit 1)),
                                            ('McLaren F1 Team', (select id from countries where abbreviation = 'GBR' limit 1)),
                                            ('Haas F1 Team', (select id from countries where abbreviation = 'USA' limit 1)),
                                            ('Renault Sport Formula One Team', (select id from countries where abbreviation = 'FRA' limit 1)),
                                            ('Manor Grand Prix', (select id from countries where abbreviation = 'GBR' limit 1)),
                                            ('SportPesa Racing Point', (select id from countries where abbreviation = 'GBR' limit 1)),
                                            ('Alfa Romeo Racing', (select id from countries where abbreviation = 'ITA' limit 1)),
                                            ('Alpine F1 Team', (select id from countries where abbreviation = 'FRA' limit 1)),
                                            ('Aston Martin Cognizant Formula One Team', (select id from countries where abbreviation = 'GBR' limit 1)),
                                            ('ROKiT Williams Racing', (select id from countries where abbreviation = 'GBR' limit 1));

INSERT INTO pilots (first_name, last_name, birthdate, citizenship_country_id) VALUES ('Lewis', 'Hamilton', '1985-01-07', (select id from countries where abbreviation = 'GBR' limit 1)),
                                                                                     ('Nico', 'Rosberg', '1985-06-27', (select id from countries where abbreviation = 'GER' limit 1)),
                                                                                     ('Sebastian', 'Vettel', '1987-07-03', (select id from countries where abbreviation = 'GER' limit 1)),
                                                                                     ('Kimi', 'Raikkonen', '1979-10-17', (select id from countries where abbreviation = 'FIN' limit 1)),
                                                                                     ('Valtteri', 'Bottas', '1989-08-28', (select id from countries where abbreviation = 'FIN' limit 1)),
                                                                                     ('Felipe', 'Massa', '1981-04-25', (select id from countries where abbreviation = 'BRA' limit 1)),
                                                                                     ('Даниил', 'Квят', '1994-04-26', (select id from countries where abbreviation = 'RUS' limit 1)),
                                                                                     ('Daniel', 'Ricciardo', '1989-07-01', (select id from countries where abbreviation = 'AUS' limit 1)),
                                                                                     ('Sergio', 'Perez', '1990-01-26', (select id from countries where abbreviation = 'MEX' limit 1)),
                                                                                     ('Nicolas', 'Hulkenberg', '1987-08-19', (select id from countries where abbreviation = 'GER' limit 1)),
                                                                                     ('Romain', 'Grosjean', '1986-04-17', (select id from countries where abbreviation = 'FRA' limit 1)),
                                                                                     ('Max', 'Verstappen', '1997-09-30', (select id from countries where abbreviation = 'NED' limit 1)),
                                                                                     ('Felipe', 'Nasr', '1992-08-21', (select id from countries where abbreviation = 'BRA' limit 1)),
                                                                                     ('Pastor', 'Maldonado', '1985-03-09', (select id from countries where abbreviation = 'VEN' limit 1)),
                                                                                     ('Carlos', 'Sainz Jr.', '1994-09-01', (select id from countries where abbreviation = 'ESP' limit 1)),
                                                                                     ('Jenson', 'Button', '1980-01-19', (select id from countries where abbreviation = 'GBR' limit 1)),
                                                                                     ('Fernando', 'Alonso Diaz', '1981-07-29', (select id from countries where abbreviation = 'ESP' limit 1)),
                                                                                     ('Marcus', 'Ericsson', '1990-09-02', (select id from countries where abbreviation = 'SWE' limit 1)),
                                                                                     ('Kevin', 'Magnussen', '1992-10-05', (select id from countries where abbreviation = 'DEN' limit 1)),
                                                                                     ('Jolyon', 'Palmer', '1991-01-20', (select id from countries where abbreviation = 'GBR' limit 1)),
                                                                                     ('Pascal', 'Wehrlein', '1994-10-18', (select id from countries where abbreviation = 'GER' limit 1)),
                                                                                     ('Stoffel', 'Vandoorne', '1992-03-26', (select id from countries where abbreviation = 'BEL' limit 1)),
                                                                                     ('Esteban', 'Ocon', '1996-09-17', (select id from countries where abbreviation = 'FRA' limit 1)),
                                                                                     ('Charles', 'Leclerc', '1997-10-16', (select id from countries where abbreviation = 'MON' limit 1)),
                                                                                     ('Pierre', 'Gasly', '1996-02-07', (select id from countries where abbreviation = 'FRA' limit 1)),
                                                                                     ('Lance', 'Stroll', '1998-10-29', (select id from countries where abbreviation = 'CAN' limit 1)),
                                                                                     ('Brendon', 'Hartley', '1989-11-10', (select id from countries where abbreviation = 'NZL' limit 1)),
                                                                                     ('Alexander', 'Albon', '1996-03-23', (select id from countries where abbreviation = 'THA' limit 1)),
                                                                                     ('Lando', 'Norris', '1999-11-13', (select id from countries where abbreviation = 'GBR' limit 1)),
                                                                                     ('Antonio', 'Giovinazzi', '1993-12-14', (select id from countries where abbreviation = 'ITA' limit 1)),
                                                                                     ('Romain', 'Grosjean', '1986-04-17', (select id from countries where abbreviation = 'FRA' limit 1)),
                                                                                     ('Robert', 'Kubica', '1984-12-07', (select id from countries where abbreviation = 'POL' limit 1)),
                                                                                     ('Yuki', 'Tsunoda', '2000-05-11', (select id from countries where abbreviation = 'JPN' limit 1)),
                                                                                     ('George', 'Russel', '1998-02-15', (select id from countries where abbreviation = 'GBR' limit 1)),
                                                                                     ('Nicholas', 'Latifi', '1995-06-29', (select id from countries where abbreviation = 'CAN' limit 1)),
                                                                                     ('Mick', 'Schumacher', '1999-03-22', (select id from countries where abbreviation = 'GER' limit 1)),
                                                                                     ('Guanyu', 'Zhou', '1999-05-30', (select id from countries where abbreviation = 'CHN' limit 1)),
                                                                                     ('Nyck', 'de Vries', '1995-02-06', (select id from countries where abbreviation = 'NED' limit 1));

INSERT INTO pilots_teams_assignment (pilot_id, team_id, start_date, end_date) VALUES ((select id from pilots where last_name = 'Hamilton' limit 1), (select id from teams where name = 'Mercedes AMG Petronas Motorsport'), '2013-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Rosberg' limit 1), (select id from teams where name = 'Mercedes AMG Petronas Motorsport'), '2010-01-01', '2016-12-31'),
                                                                                     ((select id from pilots where last_name = 'Vettel' limit 1), (select id from teams where name = 'Scuderia Ferrari'), '2015-01-01', '2020-12-31'),
                                                                                     ((select id from pilots where last_name = 'Raikkonen' limit 1), (select id from teams where name = 'Scuderia Ferrari'), '2015-01-01', '2018-12-31'),
                                                                                     ((select id from pilots where last_name = 'Bottas' limit 1), (select id from teams where name = 'ROKiT Williams Racing'), '2015-01-01', '2016-12-31'),
                                                                                     ((select id from pilots where last_name = 'Massa' limit 1), (select id from teams where name = 'ROKiT Williams Racing'), '2015-01-01', '2017-12-31'),
                                                                                     ((select id from pilots where last_name = 'Квят' limit 1), (select id from teams where name = 'Aston Martin Red Bull Racing'), '2015-01-01', '2015-12-31'),
                                                                                     ((select id from pilots where last_name = 'Ricciardo' limit 1), (select id from teams where name = 'Aston Martin Red Bull Racing'), '2015-01-01', '2018-12-31'),
                                                                                     ((select id from pilots where last_name = 'Perez' limit 1), (select id from teams where name = 'Force India F1 Team'), '2015-01-01', '2018-12-31'),
                                                                                     ((select id from pilots where last_name = 'Hulkenberg' limit 1), (select id from teams where name = 'Force India F1 Team'), '2015-01-01', '2015-12-31'),
                                                                                     ((select id from pilots where last_name = 'Grosjean' limit 1), (select id from teams where name = 'Lotus Renault'), '2015-01-01', '2015-12-31'),
                                                                                     ((select id from pilots where last_name = 'Verstappen' limit 1), (select id from teams where name = 'Scuderia AlphaTauri'), '2015-01-01', '2015-12-31'),
                                                                                     ((select id from pilots where last_name = 'Nasr' limit 1), (select id from teams where name = 'Sauber F1 Team'), '2015-01-01', '2016-12-31'),
                                                                                     ((select id from pilots where last_name = 'Maldonado' limit 1), (select id from teams where name = 'Lotus Renault'), '2015-01-01', '2015-12-31'),
                                                                                     ((select id from pilots where last_name = 'Sainz Jr.' limit 1), (select id from teams where name = 'Scuderia AlphaTauri'), '2015-01-01', '2016-12-31'),
                                                                                     ((select id from pilots where last_name = 'Button' limit 1), (select id from teams where name = 'McLaren F1 Team'), '2015-01-01', '2016-12-31'),
                                                                                     ((select id from pilots where last_name = 'Alonso Diaz' limit 1), (select id from teams where name = 'McLaren F1 Team'), '2015-01-01', '2020-12-31'),
                                                                                     ((select id from pilots where last_name = 'Ericsson' limit 1), (select id from teams where name = 'Sauber F1 Team'), '2015-01-01', '2015-12-31'),
                                                                                     ((select id from pilots where last_name = 'Verstappen' limit 1), (select id from teams where name = 'Aston Martin Red Bull Racing'), '2016-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Hulkenberg' limit 1), (select id from teams where name = 'Renault Sport Formula One Team'), '2016-01-01', '2019-12-31'),
                                                                                     ((select id from pilots where last_name = 'Grosjean' limit 1), (select id from teams where name = 'Haas F1 Team'), '2016-01-01', '2020-12-31'),
                                                                                     ((select id from pilots where last_name = 'Квят' limit 1), (select id from teams where name = 'Scuderia AlphaTauri'), '2016-01-01', '2019-12-31'),
                                                                                     ((select id from pilots where last_name = 'Magnussen' limit 1), (select id from teams where name = 'Haas F1 Team'), '2016-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Palmer' limit 1), (select id from teams where name = 'Renault Sport Formula One Team'), '2016-01-01', '2017-12-31'),
                                                                                     ((select id from pilots where last_name = 'Wehrlein' limit 1), (select id from teams where name = 'Manor Grand Prix'), '2016-01-01', '2016-12-31'),
                                                                                     ((select id from pilots where last_name = 'Vandoorne' limit 1), (select id from teams where name = 'McLaren F1 Team'), '2016-01-01', '2018-12-31'),
                                                                                     ((select id from pilots where last_name = 'Bottas' limit 1), (select id from teams where name = 'Mercedes AMG Petronas Motorsport'), '2017-01-01', '2021-12-31'),
                                                                                     ((select id from pilots where last_name = 'Ocon' limit 1), (select id from teams where name = 'Force India F1 Team'), '2017-01-01', '2019-12-31'),
                                                                                     ((select id from pilots where last_name = 'Sainz Jr.' limit 1), (select id from teams where name = 'Renault Sport Formula One Team'), '2017-01-01', '2018-12-31'),
                                                                                     ((select id from pilots where last_name = 'Stroll' limit 1), (select id from teams where name = 'ROKiT Williams Racing'), '2017-01-01', '2018-12-31'),
                                                                                     ((select id from pilots where last_name = 'Wehrlein' limit 1), (select id from teams where name = 'Sauber F1 Team'), '2017-01-01', '2017-12-31'),
                                                                                     ((select id from pilots where last_name = 'Leclerc' limit 1), (select id from teams where name = 'Sauber F1 Team'), '2018-01-01', '2018-12-31'),
                                                                                     ((select id from pilots where last_name = 'Gasly' limit 1), (select id from teams where name = 'Scuderia AlphaTauri'), '2018-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Hartley' limit 1), (select id from teams where name = 'Scuderia AlphaTauri'), '2018-01-01', '2018-12-31'),
                                                                                     ((select id from pilots where last_name = 'Leclerc' limit 1), (select id from teams where name = 'Scuderia Ferrari'), '2019-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Sainz Jr.' limit 1), (select id from teams where name = 'McLaren F1 Team'), '2019-01-01', '2020-12-31'),
                                                                                     ((select id from pilots where last_name = 'Albon' limit 1), (select id from teams where name = 'Aston Martin Red Bull Racing'), '2019-01-01', '2021-12-31'),
                                                                                     ((select id from pilots where last_name = 'Ricciardo' limit 1), (select id from teams where name = 'Renault Sport Formula One Team'), '2019-01-01', '2020-12-31'),
                                                                                     ((select id from pilots where last_name = 'Perez' limit 1), (select id from teams where name = 'SportPesa Racing Point'), '2019-01-01', '2020-12-31'),
                                                                                     ((select id from pilots where last_name = 'Norris' limit 1), (select id from teams where name = 'McLaren F1 Team'), '2019-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Raikkonen' limit 1), (select id from teams where name = 'Alfa Romeo Racing'), '2019-01-01', '2021-12-31'),
                                                                                     ((select id from pilots where last_name = 'Stroll' limit 1), (select id from teams where name = 'SportPesa Racing Point'), '2019-01-01', '2020-12-31'),
                                                                                     ((select id from pilots where last_name = 'Giovinazzi' limit 1), (select id from teams where name = 'Alfa Romeo Racing'), '2019-01-01', '2021-12-31'),
                                                                                     ((select id from pilots where last_name = 'Kubica' limit 1), (select id from teams where name = 'ROKiT Williams Racing'), '2019-01-01', '2021-12-31'),
                                                                                     ((select id from pilots where last_name = 'Ocon' limit 1), (select id from teams where name = 'Renault Sport Formula One Team'), '2020-01-01', '2020-12-31'),
                                                                                     ((select id from pilots where last_name = 'Hulkenberg' limit 1), (select id from teams where name = 'SportPesa Racing Point'), '2020-01-01', '2020-12-31'),
                                                                                     ((select id from pilots where last_name = 'Russel' limit 1), (select id from teams where name = 'ROKiT Williams Racing'), '2020-01-01', '2021-12-31'),
                                                                                     ((select id from pilots where last_name = 'Perez' limit 1), (select id from teams where name = 'Aston Martin Red Bull Racing'), '2021-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Sainz Jr.' limit 1), (select id from teams where name = 'Scuderia Ferrari'), '2021-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Ricciardo' limit 1), (select id from teams where name = 'McLaren F1 Team'), '2021-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Alonso Diaz' limit 1), (select id from teams where name = 'Alpine F1 Team'), '2021-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Ocon' limit 1), (select id from teams where name = 'Alpine F1 Team'), '2021-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Vettel' limit 1), (select id from teams where name = 'Aston Martin Cognizant Formula One Team'), '2021-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Stroll' limit 1), (select id from teams where name = 'Aston Martin Cognizant Formula One Team'), '2021-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Tsunoda' limit 1), (select id from teams where name = 'Scuderia AlphaTauri'), '2021-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Latifi' limit 1), (select id from teams where name = 'ROKiT Williams Racing'), '2021-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Russel' limit 1), (select id from teams where name = 'Mercedes AMG Petronas Motorsport'), '2022-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Bottas' limit 1), (select id from teams where name = 'Alfa Romeo Racing'), '2022-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Schumacher' limit 1), (select id from teams where name = 'Haas F1 Team'), '2022-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Zhou' limit 1), (select id from teams where name = 'Alfa Romeo Racing'), '2022-01-01', null),
                                                                                     ((select id from pilots where last_name = 'Albon' limit 1), (select id from teams where name = 'ROKiT Williams Racing'), '2022-01-01', null),
                                                                                     ((select id from pilots where last_name = 'de Vries' limit 1), (select id from teams where name = 'ROKiT Williams Racing'), '2022-01-01', null);

INSERT INTO grand_prix (name, country_id) VALUES ('Australia Grand Prix', (select id from countries where abbreviation = 'AUS')),
                                                 ('Malaysia Grand Prix', (select id from countries where abbreviation = 'MAS')),
                                                 ('China Grand Prix', (select id from countries where abbreviation = 'CHN')),
                                                 ('Bahrein Grand Prix', (select id from countries where abbreviation = 'BRN')),
                                                 ('Spain Grand Prix', (select id from countries where abbreviation = 'ESP')),
                                                 ('Monaco Grand Prix', (select id from countries where abbreviation = 'MON')),
                                                 ('Canada Grand Prix', (select id from countries where abbreviation = 'CAN')),
                                                 ('Austria Grand Prix', (select id from countries where abbreviation = 'AUT')),
                                                 ('British Grand Prix', (select id from countries where abbreviation = 'GBR')),
                                                 ('Hungary Grand Prix', (select id from countries where abbreviation = 'HUN')),
                                                 ('Belgium Grand Prix', (select id from countries where abbreviation = 'BEL')),
                                                 ('Italian Grand Prix', (select id from countries where abbreviation = 'ITA')),
                                                 ('Singapore Grand Prix', (select id from countries where abbreviation = 'SGP')),
                                                 ('Japan Grand Prix', (select id from countries where abbreviation = 'JPN')),
                                                 ('Russia Grand Prix', (select id from countries where abbreviation = 'RUS')),
                                                 ('USA Grand Prix', (select id from countries where abbreviation = 'USA')),
                                                 ('Mexico Grand Prix', (select id from countries where abbreviation = 'MEX')),
                                                 ('Brazil Grand Prix', (select id from countries where abbreviation = 'BRA')),
                                                 ('Abu-Dhabi Grand Prix', (select id from countries where abbreviation = 'UAE')),
                                                 ('Europe Grand Prix', (select id from countries where abbreviation = 'AZE')),
                                                 ('German Grand Prix', (select id from countries where abbreviation = 'GER')),
                                                 ('Azerbaijan Grand Prix', (select id from countries where abbreviation = 'AZE')),
                                                 ('France Grand Prix', (select id from countries where abbreviation = 'FRA')),
                                                 ('Styria Grand Prix', (select id from countries where abbreviation = 'AUT')),
                                                 ('F1 70-years Grand Prix', (select id from countries where abbreviation = 'GBR')),
                                                 ('Tuscany Grand Prix', (select id from countries where abbreviation = 'ITA')),
                                                 ('Eifel Grand Prix (Nurburgring)', (select id from countries where abbreviation = 'GER')),
                                                 ('Portugal Grand Prix', (select id from countries where abbreviation = 'POR')),
                                                 ('Emilia-Romagna Grand Prix', (select id from countries where abbreviation = 'ITA')),
                                                 ('Turkish Grand Prix', (select id from countries where abbreviation = 'TUR')),
                                                 ('Sahir Grand Prix', (select id from countries where abbreviation = 'BRN')),
                                                 ('Netherlands Grand Prix', (select id from countries where abbreviation = 'NED')),
                                                 ('Mayhem Grand Prix', (select id from countries where abbreviation = 'USA'));

INSERT INTO race_type (name) VALUES ('Qualification'), ('Race');

INSERT INTO race_schedule (grand_prix_id, datetime, race_type_id) VALUES ((select id from grand_prix where name = 'Australia Grand Prix' limit 1), '2015-03-14 09:00:00.000 +03:00', (select id from race_type where name = 'Qualification' limit 1)),
                                                                         ((select id from grand_prix where name = 'Australia Grand Prix' limit 1), '2015-03-15 08:00:00.000 +03:00', (select id from race_type where name = 'Race' limit 1)),
                                                                         ((select id from grand_prix where name = 'Malaysia Grand Prix' limit 1), '2015-03-28 12:00:00.000 +03:00', (select id from race_type where name = 'Qualification' limit 1)),
                                                                         ((select id from grand_prix where name = 'Malaysia Grand Prix' limit 1), '2015-03-29 10:00:00.000 +03:00', (select id from race_type where name = 'Race' limit 1)),
                                                                         ((select id from grand_prix where name = 'China Grand Prix' limit 1), '2015-04-11 10:00:00.000 +03:00', (select id from race_type where name = 'Qualification' limit 1)),
                                                                         ((select id from grand_prix where name = 'China Grand Prix' limit 1), '2015-04-12 09:00:00.000 +03:00', (select id from race_type where name = 'Race' limit 1)),
                                                                         ((select id from grand_prix where name = 'Bahrein Grand Prix' limit 1), '2015-04-18 18:00:00.000 +03:00', (select id from race_type where name = 'Qualification' limit 1)),
                                                                         ((select id from grand_prix where name = 'Bahrein Grand Prix' limit 1), '2015-04-19 18:00:00.000 +03:00', (select id from race_type where name = 'Race' limit 1)),
                                                                         ((select id from grand_prix where name = 'Spain Grand Prix' limit 1), '2015-05-09 15:00:00.000 +03:00', (select id from race_type where name = 'Qualification' limit 1)),
                                                                         ((select id from grand_prix where name = 'Spain Grand Prix' limit 1), '2015-05-10 15:00:00.000 +03:00', (select id from race_type where name = 'Race' limit 1)),
                                                                         ((select id from grand_prix where name = 'Monaco Grand Prix' limit 1), '2015-05-23 15:00:00.000 +03:00', (select id from race_type where name = 'Qualification' limit 1)),
                                                                         ((select id from grand_prix where name = 'Monaco Grand Prix' limit 1), '2015-05-24 15:00:00.000 +03:00', (select id from race_type where name = 'Race' limit 1));

INSERT INTO race_results (race_schedule_id, pilot_id, place, race_time) VALUES ((select id from race_schedule where grand_prix_id = (select id from grand_prix where name = 'Australia Grand Prix' limit 1) and race_type_id = (select id from race_type where name = 'Race' limit 1)), (select id from pilots where last_name = 'Hamilton' limit 1), 1, '1 hour 31 minutes 54 seconds'),
                                                                               ((select id from race_schedule where grand_prix_id = (select id from grand_prix where name = 'Australia Grand Prix' limit 1) and race_type_id = (select id from race_type where name = 'Race' limit 1)), (select id from pilots where last_name = 'Rosberg' limit 1), 2, '1 hour 31 minute 55 seconds'),
                                                                               ((select id from race_schedule where grand_prix_id = (select id from grand_prix where name = 'Australia Grand Prix' limit 1) and race_type_id = (select id from race_type where name = 'Race' limit 1)), (select id from pilots where last_name = 'Vettel' limit 1), 3, '1 hour 32 minutes 22 seconds'),
                                                                               ((select id from race_schedule where grand_prix_id = (select id from grand_prix where name = 'Australia Grand Prix' limit 1) and race_type_id = (select id from race_type where name = 'Race' limit 1)), (select id from pilots where last_name = 'Massa' limit 1), 4, '1 hour 32 minutes 25 seconds'),
                                                                               ((select id from race_schedule where grand_prix_id = (select id from grand_prix where name = 'Australia Grand Prix' limit 1) and race_type_id = (select id from race_type where name = 'Race' limit 1)), (select id from pilots where last_name = 'Nasr' limit 1), 5, '1 hour 32 minutes 32 seconds');
